/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.persona;
import static java.lang.Math.random;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Random;

/**
 *
 * @author pande
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    
    ArrayList<persona> lista=new ArrayList<persona>();
    DefaultTableModel model;
    int id;
    String cedula;
    public principal() {
        initComponents();
    }
    
    void listar() {
        
        try {
            Object[] persona = new Object[9];
            model = (DefaultTableModel) TablaDatos.getModel();//en esta linea se crea el modelo de la tabla
            
            
            for (int i = 0; i < lista.size(); i++) {
                persona[0] = lista.get(i).getCedula();
                persona[1] = lista.get(i).getApellido();
                persona[2] = lista.get(i).getNombre();
                persona[3] = lista.get(i).getProvincia();
                persona[4] = lista.get(i).getCiudad();
                persona[5] = lista.get(i).getFechaNac();
                persona[6] = lista.get(i).getNacionalidad();
                persona[7] = lista.get(i).getSexo();
                persona[8] = lista.get(i).getEstadoCivil();
                
                model.addRow(persona);
                
            }
            TablaDatos.setModel(model);

        } catch (Exception e) {
            System.out.println("Error "+e.getMessage());
        }

    }
    
    
    void limpiarTabla(DefaultTableModel model) {
        for (int i = 0; i <= TablaDatos.getRowCount(); i++) {
            model.removeRow(i);
            i = i - 1;
        }

    }
    
    void vaciar() {
        
        try {
            limpiarTabla(model);
            

        } catch (Exception e) {
            System.out.println("Error "+e.getMessage());
        }

    }
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbProvincia = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        cmbCanton = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNacionalidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbEstadoC = new javax.swing.JComboBox<>();
        rbtnHombre = new javax.swing.JRadioButton();
        rbtnMujer = new javax.swing.JRadioButton();
        spnFecha = new javax.swing.JSpinner();
        btnAgregar1 = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setToolTipText("Datos Personales");

        jLabel1.setText("Cedula");

        txtCedula.setEnabled(false);

        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });

        jLabel2.setText("Apellidos");

        jLabel4.setText("Provincia");

        cmbProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija Opcion", "Azuay", "Bolivar", "Cañar", "Carchi", "Cotopaxi", "Chimborazo", "El Oro", "Esmeraldas", "Guayas", "Imbabura", "Loja", "Los Rios", "Manabi", "Morona Santiago", "Napo", "Pastaza", "Pichincha", "Tungurahua", "Zamora Chinchipe", "Galapagos", "Sucumbias", "Orellana", "Santo Domingo", "Santa Elena" }));
        cmbProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProvinciaActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombres");

        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });

        cmbCanton.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja Canton" }));
        cmbCanton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCantonActionPerformed(evt);
            }
        });

        jLabel5.setText("Canton");

        jLabel7.setText("Nacionalidad");

        txtNacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNacionalidadActionPerformed(evt);
            }
        });

        jLabel9.setText("Estado civil");

        jLabel8.setText("Sexo");

        jLabel6.setText("Fecha Nac.");

        cmbEstadoC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija Opcion", "Soltero/a", "Casado/a", "Divorciado/a", "Viudo/a" }));

        sexo.add(rbtnHombre);
        rbtnHombre.setText("Hombre");

        sexo.add(rbtnMujer);
        rbtnMujer.setText("Mujer");

        spnFecha.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(978325260000L), null, null, java.util.Calendar.DAY_OF_WEEK_IN_MONTH));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(49, 49, 49))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtnHombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnMujer))
                    .addComponent(spnFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbCanton, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombres)
                            .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbEstadoC, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(spnFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(rbtnHombre)
                            .addComponent(rbtnMujer)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbCanton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cmbEstadoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(77, 77, 77))
        );

        btnAgregar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_user.png"))); // NOI18N
        btnAgregar1.setText("Agregar");
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/revert.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_cancel.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Apellidos", "Nombres", "Provincia", "Ciudad", "Fecha Nac", "Nacionalidad", "Sexo", "Estado Civil"
            }
        ));
        TablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(btnAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar1)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnNuevo))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void txtNacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNacionalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNacionalidadActionPerformed

    private void cmbCantonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCantonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCantonActionPerformed

    private void cmbProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProvinciaActionPerformed
        // TODO add your handling code here:
        cmbCanton.removeAllItems();
        cmbCanton.addItem("Escoja Canton");

        switch (cmbProvincia.getSelectedIndex()) {
            case 1:
                
                cmbCanton.addItem("Chordeleg");
                cmbCanton.addItem("Cuenca");
                cmbCanton.addItem("El Pan");
                cmbCanton.addItem("Girón");
                cmbCanton.addItem("Guachapala");
                cmbCanton.addItem("Gualaceo");
                cmbCanton.addItem("Nabón");
                cmbCanton.addItem("Oña");
                cmbCanton.addItem("Paute");
                cmbCanton.addItem("Ponce Enriquez");
                cmbCanton.addItem("Pucará");
                cmbCanton.addItem("San Fernando");
                cmbCanton.addItem("Santa Isabel");
                cmbCanton.addItem("Sevilla de Oro");
                cmbCanton.addItem("Sígsig");
                id=1;
                break;
            case 2:
                
                cmbCanton.addItem("Caluma");
                cmbCanton.addItem("Chillanes");
                cmbCanton.addItem("Chimbo");
                cmbCanton.addItem("Echeandía");
                cmbCanton.addItem("Guaranda");
                cmbCanton.addItem("Las Naves");
                cmbCanton.addItem("San Miguel");
                id=2;
                break;
            case 3:
                
                cmbCanton.addItem("Azogues");
                cmbCanton.addItem("Biblián");
                cmbCanton.addItem("Cañar");
                cmbCanton.addItem("Déleg");
                cmbCanton.addItem("El Tambo");
                cmbCanton.addItem("La Troncal");
                cmbCanton.addItem("Suscal");
                id=3;
                break;
            case 4:
                
                cmbCanton.addItem("Bolívar");
                cmbCanton.addItem("Espejo");
                cmbCanton.addItem("Mira");
                cmbCanton.addItem("Montúfar");
                cmbCanton.addItem("San Pedro de Huacao");
                cmbCanton.addItem("Tulcán");
                id=4;
                break;
            case 5:
                cmbCanton.addItem("La Maná");
                cmbCanton.addItem("Latacunga");
                cmbCanton.addItem("Pangua");
                cmbCanton.addItem("Pujilí");
                cmbCanton.addItem("Salcedo");
                cmbCanton.addItem("Saquisilí");
                cmbCanton.addItem("Sigchos");
                id=5;
                break;
            case 6:
                
                cmbCanton.addItem("Alausí");
                cmbCanton.addItem("Chambo");
                cmbCanton.addItem("Chunchi");
                cmbCanton.addItem("Colta");
                cmbCanton.addItem("Cumandá");
                cmbCanton.addItem("Guamote");
                cmbCanton.addItem("Guano");
                cmbCanton.addItem("Pallatanga");
                cmbCanton.addItem("Penipe");
                cmbCanton.addItem("Riobamba");
                id=6;
                break;
            case 7:
                
                cmbCanton.addItem("Arenillas");
                cmbCanton.addItem("Atahualpa");
                cmbCanton.addItem("Balsas");
                cmbCanton.addItem("Chilla");
                cmbCanton.addItem("El Guabo");
                cmbCanton.addItem("Huaquillas");
                cmbCanton.addItem("Las Lajas");
                cmbCanton.addItem("Machala");
                cmbCanton.addItem("Marcabelí");
                cmbCanton.addItem("Pasaje");
                cmbCanton.addItem("Piñas");
                cmbCanton.addItem("Portovelo");
                cmbCanton.addItem("Santa Rosa");
                cmbCanton.addItem("Zaruma");
                id=7;
                break;
            case 8:
                
                cmbCanton.addItem("Atacames");
                cmbCanton.addItem("Eloy Alfaro");
                cmbCanton.addItem("Esmeraldas");
                cmbCanton.addItem("Muisne");
                cmbCanton.addItem("Quinindé");
                cmbCanton.addItem("Rioverde");
                cmbCanton.addItem("San Lorenzo");
                id=8;
                break;
            case 9:
                
                cmbCanton.addItem("Guayaquil");
                cmbCanton.addItem("Alfredo Baquerizo Moreno");
                cmbCanton.addItem("Balao");
                cmbCanton.addItem("Balzar");
                cmbCanton.addItem("Colimes");
                cmbCanton.addItem("Coronel Marcelino Maridueña");
                cmbCanton.addItem("Daule");
                cmbCanton.addItem("Durán");
                cmbCanton.addItem("El Empalme");
                cmbCanton.addItem("El Triunfo");
                cmbCanton.addItem("General Antonio Elizalde");
                cmbCanton.addItem("Isidro Ayora");
                cmbCanton.addItem("Lomas de Sargentillo");
                cmbCanton.addItem("Milagro");
                cmbCanton.addItem("Naranjal");
                cmbCanton.addItem("Naranjito");
                cmbCanton.addItem("Nobol");
                cmbCanton.addItem("Palestina");
                cmbCanton.addItem("Pedro Carbo");
                cmbCanton.addItem("	Playas");
                cmbCanton.addItem("Salitre");
                cmbCanton.addItem("Samborondón");
                cmbCanton.addItem("Santa Lucía");
                cmbCanton.addItem("Simón Bolívar");
                cmbCanton.addItem("Yaguachi");
                id=9;
                break;
            case 10:
                
                cmbCanton.addItem("Antonio Ante");
                cmbCanton.addItem("Cotacachi");
                cmbCanton.addItem("Ibarra");
                cmbCanton.addItem("Otavalo");
                cmbCanton.addItem("Pimampiro");
                cmbCanton.addItem("Urcuquí");
                id=10;
                break;
            case 11:
                
                cmbCanton.addItem("Calvas");
                cmbCanton.addItem("Catamayo");
                cmbCanton.addItem("Celica");
                cmbCanton.addItem("Chaguarpamba");
                cmbCanton.addItem("Gonzanamá");
                cmbCanton.addItem("Loja");
                cmbCanton.addItem("Macará");
                cmbCanton.addItem("Olmedo");
                cmbCanton.addItem("Paltas");
                cmbCanton.addItem("Pindal");
                cmbCanton.addItem("Puyango");
                cmbCanton.addItem("Quilanga");
                cmbCanton.addItem("Saraguro");
                cmbCanton.addItem("Sozoranga");
                cmbCanton.addItem("Zapotillol");
                id=11;
                break;
            case 12:
                
                cmbCanton.addItem("Baba");
                cmbCanton.addItem("Babahoyo");
                cmbCanton.addItem("Buena Fe");
                cmbCanton.addItem("Mocache");
                cmbCanton.addItem("Montalvo");
                cmbCanton.addItem("Palenque");
                cmbCanton.addItem("Puebloviejo");
                cmbCanton.addItem("Quevedo");
                cmbCanton.addItem("Quinsaloma");
                cmbCanton.addItem("Urdaneta");
                cmbCanton.addItem("Valencia");
                cmbCanton.addItem("Ventanas");
                cmbCanton.addItem("Vinces");
                id=12;
                break;
            case 13:
                
                cmbCanton.addItem("Bolívar");
                cmbCanton.addItem("Chone");
                cmbCanton.addItem("El Carmen");
                cmbCanton.addItem("Flavio Alfaro");
                cmbCanton.addItem("Jama");
                cmbCanton.addItem("Jaramijó");
                cmbCanton.addItem("Jipijapa");
                cmbCanton.addItem("Junín");
                cmbCanton.addItem("Manta");
                cmbCanton.addItem("Montecristi");
                cmbCanton.addItem("Olmedo");
                cmbCanton.addItem("Paján");
                cmbCanton.addItem("Pedernales");
                cmbCanton.addItem("Pichincha");
                cmbCanton.addItem("Portoviejo");
                cmbCanton.addItem("Puerto López");
                cmbCanton.addItem("Rocafuerte");
                cmbCanton.addItem("San Vicente");
                cmbCanton.addItem("Santa Ana");
                cmbCanton.addItem("Sucre");
                cmbCanton.addItem("Tosagua");
                cmbCanton.addItem("Veinticuatro de Mayo");
                id=13;
                break;
            case 14:
                
                cmbCanton.addItem("Gualaquiza");
                cmbCanton.addItem("Huamboya");
                cmbCanton.addItem("Limón Indanza");
                cmbCanton.addItem("Logroño");
                cmbCanton.addItem("Morona");
                cmbCanton.addItem("Pablo Sexto");
                cmbCanton.addItem("Palora");
                cmbCanton.addItem("San Juan Bosco");
                cmbCanton.addItem("Santiago");
                cmbCanton.addItem("Sucúa");
                cmbCanton.addItem("Taisha");
                cmbCanton.addItem("Tiwintza");
                id=14;
                break;
            case 15:
                //napo
                
                cmbCanton.addItem("Archidona");
                cmbCanton.addItem("Carlos Julio Arosemena Tola");
                cmbCanton.addItem("El Chaco");
                cmbCanton.addItem("Quijos");
                cmbCanton.addItem("Tena");
                id=15;
                break;
            case 16:
                //pastaza
                
                cmbCanton.addItem("Arajuno");
                cmbCanton.addItem("Mera");
                cmbCanton.addItem("Pastaza");
                cmbCanton.addItem("Santa Clara");
                id=16;
                break;
            case 17:
                
                cmbCanton.addItem("Cayambe");
                cmbCanton.addItem("Mejía");
                cmbCanton.addItem("Pedro Moncayo");
                cmbCanton.addItem("Pedro Vicente Maldonado");
                cmbCanton.addItem("Puerto Quito");
                cmbCanton.addItem("Distrito Metropolitano de Quito");
                cmbCanton.addItem("Rumiñahui");
                cmbCanton.addItem("San Miguel de Los Bancos");
                id=17;
                break;
            case 18:
                
                cmbCanton.addItem("Ambato");
                cmbCanton.addItem("Baños");
                cmbCanton.addItem("Cevallos");
                cmbCanton.addItem("Mocha");
                cmbCanton.addItem("Patate");
                cmbCanton.addItem("Pelileo");
                cmbCanton.addItem("Píllaro");
                cmbCanton.addItem("Quero");
                cmbCanton.addItem("Tisaleo");
                
                id=18;
                break;
            case 19:
                
                cmbCanton.addItem("Centinela del Cóndor");
                cmbCanton.addItem("Chinchipe");
                cmbCanton.addItem("El Pangui");
                cmbCanton.addItem("Nangaritza");
                cmbCanton.addItem("Paquisha");
                cmbCanton.addItem("Yacuambi");
                cmbCanton.addItem("Yantzaza");
                cmbCanton.addItem("Zamora");
                
                
                id=19;
                break;
            case 20:
                
                
                //galapagos
                
                cmbCanton.addItem("Isabela");
                cmbCanton.addItem("San Cristóbal");
                cmbCanton.addItem("Santa Cruz");
                id=20;
                break;
            case 21:
                
                cmbCanton.addItem("Cascales");
                cmbCanton.addItem("Cuyabeno");
                cmbCanton.addItem("Gonzalo Pizarro");
                cmbCanton.addItem("Lago Agrio");
                cmbCanton.addItem("Putumayo");
                cmbCanton.addItem("Shushufindi");
                cmbCanton.addItem("Sucumbíos");
                
                
                
                id=21;
                break;
            case 22:
                
                cmbCanton.addItem("Aguarico");
                cmbCanton.addItem("Orellana");
                cmbCanton.addItem("La Joya de los Sachas");
                cmbCanton.addItem("Loreto");
                id=22;
                break;
            case 23:
                
                cmbCanton.addItem("La Concordia");
                cmbCanton.addItem("Santo Domingo");
                id=23;
                break;
            case 24:
                
                cmbCanton.addItem("La Libertad");
                cmbCanton.addItem("Salinas");
                cmbCanton.addItem("Santa Elena");
                id=24;
                break;
            default:
                break;
        }
        
    }//GEN-LAST:event_cmbProvinciaActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
        Agregar();
        vaciar();
        listar();
        nuevo();
    }//GEN-LAST:event_btnAgregar1ActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        Modificar();
        vaciar();
        listar();
        nuevo();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Eliminar();
        vaciar();
        listar();
        nuevo();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        nuevo();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void TablaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatosMouseClicked
        int row = TablaDatos.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "No se Selecciono");
        } else {
            String ce = (String) TablaDatos.getValueAt(row, 0).toString();
            String Apellidos = (String) TablaDatos.getValueAt(row, 1);
            String Nombres = (String) TablaDatos.getValueAt(row, 2);
            String Prov = (String) TablaDatos.getValueAt(row, 3);
            String Ciud = (String) TablaDatos.getValueAt(row, 4);
            String Fec = (String) TablaDatos.getValueAt(row, 5);
            String Nac = (String) TablaDatos.getValueAt(row, 6);
            String Sex = (String) TablaDatos.getValueAt(row, 7);
            String Est = (String) TablaDatos.getValueAt(row, 8);
            txtCedula.setText(ce);
            txtApellidos.setText(Apellidos);
            txtNombres.setText(Nombres);
            cmbProvincia.setSelectedItem(Prov);
            cmbCanton.setSelectedItem(Ciud);
            //spnFecha.setValue(Date.valueOf(Fec));
            if(rbtnHombre.equals(Sex)){
                rbtnHombre.isSelected();
            }else{
                rbtnMujer.isSelected();
            }
            txtNacionalidad.setText(Nac);
            cmbEstadoC.setSelectedItem(Est);

        }
    }//GEN-LAST:event_TablaDatosMouseClicked
    
    
    void generadorCedula(){
        String p1=String.valueOf(id);
        switch(id){
            case 1:
                cedula=codigo("0","1");
                break;
            case 2:
                cedula=codigo("0","2");
                break;
            case 3:
                cedula=codigo("0","3");
                break;
            case 4:
                cedula=codigo("0","4");
                break;
            case 5:
                cedula=codigo("0","5");
                break;
            case 6:
                cedula=codigo("0","6");
                break;
            case 7:
                cedula=codigo("0","7");
                break;
            case 8:
                cedula=codigo("0","8");
                break;
            case 9:
                cedula=codigo("0","9");
                break;
            case 10:
                cedula=codigo("1","0");
                break;
            case 11:
                cedula=codigo("1","1");
                break;
            case 12:
                cedula=codigo("1","2");
                break;
            case 13:
                cedula=codigo("1","3");
                break;
            case 14:
                cedula=codigo("1","4");
                break;
            case 15:
                cedula=codigo("1","5");
                break;
            case 16:
                cedula=codigo("1","6");
                break;
            case 17:
                cedula=codigo("1","7");
                break;
            case 18:
                cedula=codigo("1","8");
                break;
            case 19:
                cedula=codigo("1","9");
                break;
            case 20:
                cedula=codigo("2","0");
                break;
            case 21:
                cedula=codigo("2","1");
                break;
            case 22:
                cedula=codigo("2","2");
                break;
            case 23:
                cedula=codigo("2","3");
                break;
            case 24:
                cedula=codigo("2","4");
                break;
        }
    }
    
    void nuevo(){
        txtCedula.setText(" ");
        txtApellidos.setText(" ");
        txtNacionalidad.setText(" ");
        txtNombres.setText(" ");
        cmbProvincia.setSelectedIndex(0);
        //cmbCanton.setSelectedIndex(0);
        
        cmbEstadoC.setSelectedIndex(0);
        //spnFecha.setValue(null);
        
        
                
    }
    
    String codigo(String d1,String d2){
        Random random = new Random();
        String d3 = String.valueOf(random.nextInt(5 + 0) + 0);
        String d4 = String.valueOf(random.nextInt(9 + 0) + 0);
        String d5 = String.valueOf(random.nextInt(9 + 0) + 0);
        String d6 = String.valueOf(random.nextInt(9 + 0) + 0);
        String d7 = String.valueOf(random.nextInt(9 + 0) + 0);
        String d8 = String.valueOf(random.nextInt(9 + 0) + 0);
        String d9 = String.valueOf(random.nextInt(9 + 0) + 0);
        String cedula=d1+"-"+d2+"-"+d3+"-"+d4+"-"+d5+"-"+d6+"-"+d7+"-"+d8+"-"+d9;
        String split[]=cedula.split("-");
        int val,par=0,impar=0;
        for (int i = 0; i < split.length; i++) {
            val=Integer.parseInt(split[i]);
            if(i%2==0){
                val=(val*2);
                if(val>=10){
                    val=val-9;
                    par+=val;
                }
                else{
                    par+=val;
                }
            }
            else{
                impar+=(val*1);
            }
            
        }
        int total=par+impar;
        String d10="";
        if(total>10 && total<21){
            d10=String.valueOf(20-total);
        }
        else if(total>20 && total<31){
            d10=String.valueOf(30-total);
        }else if(total>30 && total<41){
            d10=String.valueOf(40-total);
        }else if(total>40 && total<51){
            d10=String.valueOf(50-total);
        }else if(total>50 && total<61){
            d10=String.valueOf(60-total);
        }else if(total>60 && total<71){
            d10=String.valueOf(70-total);
        }else if(total>70 && total<81){
            d10=String.valueOf(80-total);
        }else if(total>80 && total<91){
            d10=String.valueOf(90-total);
        }else if(total>90 && total<101){
            d10=String.valueOf(100-total);
        }
            
        
        
        
        return d1+d2+d3+d4+d5+d6+d7+d8+d9+d10;
        
        
    }
    
    void Modificar() {
        
        try {
            String ced = txtCedula.getText();
        String nombre=txtNombres.getText();
        String apellido=txtApellidos.getText();
        String prov=cmbProvincia.getSelectedItem().toString();
        String cant=cmbCanton.getSelectedItem().toString();
        String edad=spnFecha.getValue().toString();
        String nacionalidad=txtNacionalidad.getText();
        String sexo;
        if(rbtnHombre.isSelected()){
            sexo="Hombre";
        }
        else{
            sexo="Mujer";
        }
        String estadC=cmbEstadoC.getSelectedItem().toString();
        int c=0;
            for (int i = 0; i < lista.size(); i++) {
                if(lista.get(i).getCedula().equals(ced)){
                    persona p=new persona(cedula,nombre,apellido, prov, cant, edad, nacionalidad, sexo, estadC);
                    lista.set(i, p);
                    JOptionPane.showMessageDialog(rootPane, "Modificado Correctamente");
                    c=1;
                    break;
                }
                
            }
            if(c==0){
                JOptionPane.showMessageDialog(rootPane, "Registro no encontrado");
            }
            

        } catch (Exception e) {
        }

    }

    void Eliminar() {
        try {
            int c=0;
            String ced = txtCedula.getText();
        
            for (int i = 0; i < lista.size(); i++) {
                if(lista.get(i).getCedula().equals(ced)){
                    
                    lista.remove(i);
                    JOptionPane.showMessageDialog(rootPane, "Eliminado Correctamente");
                    c=1;
                    break;
                }
                
            }
            
            if(c==0){
                JOptionPane.showMessageDialog(rootPane, "Registro no encontrado");
            }
        } catch (Exception e) {
        }
          
        

    }
    
    boolean soloLetras(String dato){
        boolean entradaNumerica = true;
        int c=0;
        for (int i=0;i< dato.length(); i++) {
            int l=dato.charAt(i);
            if ((l>96 && l<123) || (l==32) || (l>64 && l<91)) {
                c++;
            } 
        }
        
        if(c!=dato.length()){
            entradaNumerica = false;
        }
        return entradaNumerica;

        }
    
    
   
    void Agregar() {
        try {
            generadorCedula();
            txtCedula.setText(cedula);
            cedula=txtCedula.getText();
            String nombre=txtNombres.getText();
            String apellido=txtApellidos.getText();
            String prov=cmbProvincia.getSelectedItem().toString();
            String cant=cmbCanton.getSelectedItem().toString();
            String edad=spnFecha.getValue().toString();
            String nacionalidad=txtNacionalidad.getText();
            String sexo;
            if(rbtnHombre.isSelected()){
                sexo="Hombre";
            }
            else{
                sexo="Mujer";
            }
            String estadC=cmbEstadoC.getSelectedItem().toString();
            
            if(!soloLetras(nombre)){
                JOptionPane.showMessageDialog(rootPane, "Ingrese solo letras para el nombre");
            } else if(!soloLetras(apellido)){
                JOptionPane.showMessageDialog(rootPane, "Ingrese solo letras para el apellido");
            } else if(cmbProvincia.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(rootPane, "Escoja una Provincia");
            } else if(cmbCanton.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(rootPane, "Escoja un Canton");
            } else if(edad==null){
                JOptionPane.showMessageDialog(rootPane, "Asigne una edad");
            } else if(!soloLetras(nacionalidad)){
                JOptionPane.showMessageDialog(rootPane, "Ingrese solo letras para la nacionalidad");
            } else if(!rbtnHombre.isSelected() && !rbtnMujer.isSelected()){
                JOptionPane.showMessageDialog(rootPane, "Escoja un sexo");
            } else if(cmbEstadoC.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(rootPane, "Escoja un Estado Civil");
            }else{
                persona p=new persona(cedula,nombre,apellido, prov, cant, edad, nacionalidad, sexo, estadC);
                lista.add(p);
                JOptionPane.showMessageDialog(rootPane, "Datos Ingresados Correctamente");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error "+e.getMessage());
        }
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDatos;
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cmbCanton;
    private javax.swing.JComboBox<String> cmbEstadoC;
    private javax.swing.JComboBox<String> cmbProvincia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnHombre;
    private javax.swing.JRadioButton rbtnMujer;
    private javax.swing.ButtonGroup sexo;
    private javax.swing.JSpinner spnFecha;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNacionalidad;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
